### ISSUE TITLE
unable to generate signature

### ISSUE THREAD

**Issue by toriacht** [sbouclier/kraken-java-api-client#2]
Hi @sbouclier 

Thank you for sharing. While it appears development has stopped maybe you can answer a query? When trying to use the private api examples i get the error "unable to generate signature" eg. get trade balances, get open orders (I have no orders!, just a new empty account)

`com.github.sbouclier.KrakenApiException: [unable to generate signature]
	at com.github.sbouclier.HttpJsonClient.generateSignature(HttpJsonClient.java:143)
	at com.github.sbouclier.HttpJsonClient.executePrivateQuery(HttpJsonClient.java:79)
	at com.github.sbouclier.HttpJsonClient.executePrivateQuery(HttpJsonClient.java:69)
	at com.github.sbouclier.HttpApiClient.callPrivate(HttpApiClient.java:123)
	at com.github.sbouclier.KrakenAPIClient.getTradesHistory(KrakenAPIClient.java:364)`

any tips much appreciated. Do you think development might restart. I might be able to help?

**Comment by toriacht** [comment]
1. Closing issue. It appears it was an issue with my key/secret. works fine for newly generated key
2. Question still remains as to whether you might intend developing this further?

**Comment by sbouclier** [comment]
Hi @toriacht,

I stopped API development due to the instability of Kraken platform at the time. Furthermore, I found after my initial develpment a great API you can use for Kraken and others exchanges: https://github.com/knowm/XChange/tree/develop/xchange-kraken
If you plan to trade over Kraken API, I suggest you to use it.

Regards.

**Comment by toriacht** [comment]
Hi @sbouclier 

Thank you for your reply. I found that API too and i am looking at it also...  however I liked your one too, the simple examples and docs are very helpful
